#!bin/bash

function bk_dir_name(){
bk_to="";
  dirs=$(pwd);
    IFS='/' read -ra data <<<"$dirs";
    for ((i=${#data[@]}-1;i>=0;i--)); do
      if [[ "${data[i]}" == *$1* ]]; then cd $bk_to;
        else bk_to="../$bk_to";
      fi
    done
  }

function bk_number(){
bk_to="";
   i=0; 
   while((i++<n));do bk_to="../$bk_to"; done 
    cd $bk_to; 
  }



n=$1;
if [ -z $n ] then echo "not specified how many levels up to back";
fi

if [[ $n =~ ^[0-9]{0,10}$ ]]; then bk_number $n;
elif [[ $(pwd) == *$n* ]]; then bk_dir_name $n; 
else echo "could not find $n";
fi
  
